package src;

import java.awt.*;

/**
 * PlotDecorator is an abstract class inheriting PlotCommon and acting as 
 * a Decorator for PlotDot class.
 */
abstract class PlotDecorator extends PlotCommon {
    protected PlotCommon component;

    /**
     * This will set the component for the decorator class to decorate.
     * @param component The PlotCommon object to be decorated.
     */
    public void setComponent(PlotCommon component){
        this.component = component;
    }

    /**
     * The setNumber will call its parents setNumber method.
     * @param num The Random number generated by RandomNumbers class.
     */
    @Override
    public void setNumber(int num){
        super.setNumber(num);
    }

    /**
     * The operation will decorate the graphics class with squares and bars 
     * depending on the type of PlotCommon its holds.
	 * @param graphic Graphics object which needs to be decorated.
	 */
    @Override
    public void operation(Graphics graphic) {
       if(component!=null)
        component.operation(graphic);
    }
}
