package src;

import java.awt.*;
import java.util.*;
import java.util.List;

/**
 * PlotCommon is an abstract class for the Decorator classes as well as 
 * Concrete classes.
 */
abstract class PlotCommon {
    protected List<Integer> rndNum  = new ArrayList<>(25);

    /**
     * The setNumber will take in the random number generated by 
     * RandomNumbers class and will add it to its list.
     * It will also update the mean of singleton class.
     * The size of the list will always remain 25 so as to be plotted 
     * on the frame.
     * @param num The Random number generated by RandomNumbers class.
     */
    public void setNumber(int num){
        Evaluator.mean *= rndNum.size();
		if(rndNum.size() == 25){
            Evaluator.mean -= rndNum.remove(0);
		}
		rndNum.add(num);
        Evaluator.mean += num;
        Evaluator.mean /= rndNum.size();
	}

    /**
	 * The operation is declaration for Decorator classes 
     * that will plot the points on graphics.
	 * @param graphic Graphics object on which points are to be plotted.
	 */
    public void operation(Graphics graphic){
    };
}
